MyJunkYourStuff/Controllers/HomeController.cs
using MyJunkYourStuff.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace MyJunkYourStuff.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILocationRepository _locationRepository;

        /// <summary>
        /// Initializes a new instance of the HomeController class.
        /// </summary>
        /// <param name="locationRepository"></param>
        public HomeController(ILocationRepository locationRepository)
        {
            _locationRepository = locationRepository;
        }

        public async Task<ActionResult> Index()
        {
            // NOTE: Will need to change how dates work to work with DocumentDb. See http://blogs.msdn.com/b/documentdb/archive/2014/11/18/working-with-dates-in-azure-documentdb.aspx.
            //       Also, DocumentDb does not support OrderBy in LINQ. Need to use an OrderBy stored procedure.

            // Get 5 garage sales coming in the next 7 days.
            var upcomingLocations = await _locationRepository.GetUpcomingLocationsAsync(new TimeSpan(7,0,0,0,0), 5);

            return View(upcomingLocations);
        }

        public ActionResult About()
        {
            return View();
        }


    }
}

MyJunkYourStuff/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using MyJunkYourStuff.Models;
using System.IO;

namespace MyJunkYourStuff.Controllers
{
    public class LocationsController : Controller
    {
        private readonly ILocationRepository _locationRepository;
        private readonly IImageRepository _imageRepository;

        /// <summary>
        /// Initializes a new instance of the LocationsController class.
        /// </summary>
        /// <param name="locationRepository"></param>
        public LocationsController(ILocationRepository locationRepository, IImageRepository imageRepository)
        {
            _imageRepository = imageRepository;
            _locationRepository = locationRepository;
        }

        // GET: Locations
        public async Task<ActionResult> Index()
        {
            var locations = await _locationRepository.GetAllLocationsAsync();
            return View(locations);
        }

        // GET: Locations/Details/5
        public async Task<ActionResult> Details(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = await _locationRepository.FindAsync(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // GET: Locations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Locations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Title,StartTime,JunkerName,Description,Address")] Location location, HttpPostedFileBase imageFile)
        {
            if (ModelState.IsValid)
            {
                location.Id = Guid.NewGuid();
                if (imageFile != null && imageFile.ContentLength > 0)
                {
                    if (imageFileIsValid(imageFile))
                    {
                        string imageStoreName = String.Concat(location.Id.ToString(), Path.GetExtension(imageFile.FileName));
                        location.MainImageName = _imageRepository.Add(imageStoreName, imageFile);    
                    }
                    else
                    {
                        return View(location);
                    }
                }
                await _locationRepository.AddAsync(location);
                return RedirectToAction("Index");
            }

            return View(location);
        }

        // GET: Locations/Edit/5
        public async Task<ActionResult> Edit(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = await _locationRepository.FindAsync(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // POST: Locations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Title,StartTime,MainImageName,JunkerName,Description,Address")] Location location)
        {
            if (ModelState.IsValid)
            {
                await _locationRepository.EditAsync(location);
                return RedirectToAction("Index");
            }
            return View(location);
        }

        // GET: Locations/Delete/5
        public async Task<ActionResult> Delete(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = await _locationRepository.FindAsync(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // POST: Locations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            Location location = await _locationRepository.FindAsync(id);
            if (!string.IsNullOrWhiteSpace(location.MainImageName))
            {
                _imageRepository.Delete(location.MainImageName);
            }

            await _locationRepository.DeleteAsync(id);
            
            return RedirectToAction("Index");
        }



        private bool imageFileIsValid(HttpPostedFileBase imageFile)
        {
            // check the file size (max 4 Mb)
            // NOTE: if you want larger files you'll also need to update the web.config to include httpRuntime maxRequestLength to increase
            // the default allowed size.
            if (imageFile.ContentLength > 1024 * 1024 * 4)
            {
                ModelState.AddModelError("MainImageName", "File size can't exceed 4 MB");
                return false;
            }

            // check file extension
            string extension = Path.GetExtension(imageFile.FileName).ToLower();

            if (extension != ".png" && extension != ".jpg" )
            {
                ModelState.AddModelError("MainImageName", "Supported file extensions: png, jpg");
                return false;
            }

            return true;
        }
    }
}

MyJunkYourStuff/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>MyJunkYourStuff</h3>

<p>The MyJunkYourStuff site is a way to share upcoming Garage sale locations.  We all have stuff we want to get rid of.  What better way to
    do that than to have a garage sale and pawn all that junk off onto someone else (while making money!).  Of course, we highly suggest you
    take that money and donate it to charity, but keep a little for a nice celebration ... or to use to get more stuff to keep the cycle going.</p>

<p>This application (if you can call it that) is part of a Hands On Lab (HOL) originally created by <a href="http://twitter.com/mikewo">Mike Wood</a> 
    and <a href="https://twitter.com/MichaelCollier">Michael Collier</a> for a half day workshop on <a href="http://azure.com">Microsoft Azure</a>. 
    The workshop was given at the awesome <a href="http://codemash.org">CodeMash</a> conference in Sandusky, OH in 2015.</p>
<p>We'd like to point out that this is a demo app only.  A simple example illistrating specific points of the Azure platform.  It shouldn't
    be taken for production code.</p>

MyJunkYourStuff/Views/Home/Index.cshtml
@model IEnumerable<MyJunkYourStuff.Models.Location>
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>My Junk Your Stuff</h1>
    <p class="lead">The Law of Conservation of Mass states that mass can neither be created nor destroyed, although it can be rearranged in space.</p>
    <p>This site is dedicated to moving the mass of your junk to other people in the form of garage sales, or helping others reduce the mass in their lives
    by rearranging it to yours.</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Upcoming Sales</h2>
        <p>
            The upcoming options for freeing other people from thier junk and making it your stuff:
        </p>
        @foreach (var item in Model)
        {
            @String.Format("{0:MM/dd/yy}", item.StartTime.Date) 
            @Html.Raw("&nbsp;-&nbsp;")
            @Html.ActionLink(item.Title, "Details", "Locations", new { id = item.Id }, null) 
            <br />
        }
        <p><a class="btn btn-default" href="/Locations">More Sales &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>About</h2>
        <p>Learn more about the MyJunkYourStuff site.</p>
        <p><a class="btn btn-default" href="/home/about">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get the code</h2>
        <p>The code for this sample and more examples can be found on GitHub.</p>
        <p><a class="btn btn-default" href="https://github.com/mikewo/MyJunkYourStuff">Git the Code</a></p>
    </div>
</div>